=== szaloczy/Y4O4X0WebXML/Y4O4X0_1015/XMLSchemaY4O4X0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="korTipus">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"></xs:minInclusive>
            <xs:maxExclusive value="100"></xs:maxExclusive>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="csillagTipus">
        <xs:restriction base="xs:integer">
            <xs:minExclusive value="0"></xs:minExclusive>
            <xs:maxExclusive value="5"></xs:maxExclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="szemelyzet">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"></xs:element>
            <xs:element name="Vegzettseg" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="FoszakacsTipus">
        <xs:complexContent>
            <xs:extension base="szemelyzet">
                <xs:sequence>
                    <xs:element name="Eletkor" type="korTipus"></xs:element>
                </xs:sequence>
                <xs:attribute name="Fkod" type="xs:string" use="required"></xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="SzakacsTipus">
        <xs:complexContent>
            <xs:extension base="szemelyzet">
                <xs:sequence>
                    <xs:element name="Reszleg"></xs:element>
                </xs:sequence>
                <xs:attribute name="Szkod" type="xs:string" use="required"></xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="GyakornokTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"></xs:element>
            <xs:element name="Gyakorlat">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Kezdet" type="xs:string"></xs:element>
                        <xs:element name="Idotartam" type="xs:string"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Muszak" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
        <xs:attribute name="Gykod" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="VendegTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"></xs:element>
            <xs:element name="Eletkor" type="korTipus"></xs:element>
            <xs:element name="Cim" type="CimTipus"></xs:element>
        </xs:sequence>
        <xs:attribute name="Vkod" use="required"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="RendelesTipus">
        <xs:sequence>
            <xs:element name="Osszeg" type="xs:integer"></xs:element>
            <xs:element name="Etel" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
        <xs:attribute name="Rkod" type="xs:string"></xs:attribute>
        <xs:attribute name="EVRkod" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="CimTipus">
        <xs:sequence>
            <xs:element name="Varos" type="xs:string"></xs:element>
            <xs:element name="Utca" type="xs:string"></xs:element>
            <xs:element name="Hazszam" type="xs:string"></xs:element>
        </xs:sequence>
        <xs:attribute name="Rkod" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:element name="Vendeglatas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Etterem">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Csillag" type="csillagTipus"></xs:element>
                            <xs:element name="Cim" type="CimTipus"></xs:element>
                            <xs:element name="Nev" type="xs:string"></xs:element>
                            <xs:element name="Foszakacs" type="FoszakacsTipus"></xs:element>
                            <xs:element name="Szakacs" type="SzakacsTipus"></xs:element>
                            <xs:element name="Gyakornok" type="GyakornokTipus"></xs:element>
                            <xs:element name="Vendeg" type="VendegTipus"></xs:element>
                            <xs:element name="Rendeles" type="RendelesTipus"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="Ekod" type="xs:string"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <!-- <xs:key name="E_V">
            <xs:selector xpath="ghgfd"></xs:selector>
            <xs:field xpath="@"></xs:field>
        </xs:key> -->
    </xs:element>
</xs:schema>

=== szaloczy/Y4O4X0WebXML/Y4O4X0_1015/XMLY4O4X0.xml
<?xml version="1.0" encoding="UTF-8"?>
<Vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="XMLSchemaY4O4X0.xsd">
    <Etterem Ekod="E1">
        <Csillag>4</Csillag>
        <Cim>
            <Varos></Varos>
            <Utca></Utca>
            <Hazszam></Hazszam>
        </Cim>
        <Nev></Nev>
        <Foszakacs Fkod="F1">
            <Nev></Nev>
            <Vegzettseg></Vegzettseg>
            <Eletkor>14</Eletkor>
        </Foszakacs>
        <Szakacs Szkod="Sz1">
            <Nev></Nev>
            <Vegzettseg></Vegzettseg>
            <Reszleg></Reszleg>
        </Szakacs>
        <Gyakornok Gykod="Gy1">
            <Nev></Nev>
            <Gyakorlat>
                <Kezdet></Kezdet>
                <Idotartam></Idotartam>
            </Gyakorlat>
            <Muszak></Muszak>
        </Gyakornok>
        <Vendeg Vkod="V1">
            <Nev></Nev>
            <Eletkor>15</Eletkor>
            <Cim>
                <Varos></Varos>
                <Utca></Utca>
                <Hazszam></Hazszam>
            </Cim>
        </Vendeg>
        <Rendeles Rkod="R1" EVRkod="EVR1">
            <Osszeg>5</Osszeg>
            <Etel></Etel>
        </Rendeles>
    </Etterem>
</Vendeglatas>
