=== szaloczy/Y4O4X0WebXML/Y4O4X0_1015/Y4O4X0_orarend1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="idTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="O[0-9]+"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="napTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Hétfő"></xs:enumeration>
            <xs:enumeration value="Kedd"></xs:enumeration>
            <xs:enumeration value="Szerda"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="oraTipus">
        <xs:restriction base="xs:string">   
            <xs:enumeration value="elmelet"></xs:enumeration>
            <xs:enumeration value="gyakorlat"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="ora">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="targy" type="xs:string"></xs:element>
                <xs:element name="idopont">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nap" type="napTipus"></xs:element>
                            <xs:element name="tol" type="xs:string"></xs:element>
                            <xs:element name="ig" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="helyszin"></xs:element>
                <xs:element name="oktato"></xs:element>
                <xs:element name="szak"></xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="idTipus" use="required"></xs:attribute>
            <xs:attribute name="tipus" type="oraTipus"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="SZK_orarend_tipus">
        <xs:sequence>
            <xs:element ref="ora" minOccurs="1" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:element name="SZK_orarend" type="SZK_orarend_tipus"></xs:element>
</xs:schema>

=== szaloczy/Y4O4X0WebXML/Y4O4X0_1126/xPathY4O4X0/bin/resources/Y4O4X0_orarend2.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<SZK_orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Y4O4X0_orarend1.xsd">
        
    <ora id="O0" tipus="elmelet">
                
        <targy>Elektrotechnika és elektronika (Ea)</targy>
                
        <idopont>
                        
            <nap>Hétfő</nap>
                        
            <tol>8:00</tol>
                        
            <ig>10:00</ig>
                    
        </idopont>
                
        <helyszin>A2/III. Előadó</helyszin>
                
        <oktato>Szabó Nórbert</oktato>
                
        <szak>Árnyékolás technikus</szak>
            
    </ora>
        
    <ora id="O1" tipus="elmelet">
                
        <targy>Webtechnológia I (WI)</targy>
                
        <idopont>
                        
            <nap>Hétfő</nap>
                        
            <tol>10:00</tol>
                        
            <ig>12:00</ig>
                    
        </idopont>
                
        <helyszin>A2/I. Előadó</helyszin>
                
        <oktato>Agárdi Anita</oktato>
                
        <szak>Árnyékolás technikus</szak>
            
    </ora>
        
    <ora id="O3" tipus="gyakorlat">
                
        <targy>Angol szaknyelv (Av)</targy>
                
        <idopont>
                        
            <nap>Hétfő</nap>
                        
            <tol>12:00</tol>
                        
            <ig>14:00</ig>
                    
        </idopont>
                
        <helyszin>XXXVII</helyszin>
                
        <oktato>Dorkó Dóra</oktato>
                
        <szak>Árnyékolás technikus</szak>
            
    </ora>
        
    <ora id="O4" tipus="gyakorlat">
                
        <targy>Webtechnológia I (WI)</targy>
                
        <idopont>
                        
            <nap>Hétfő</nap>
                        
            <tol>14:00</tol>
                        
            <ig>16:00</ig>
                    
        </idopont>
                
        <helyszin>Inf/101</helyszin>
                
        <oktato>Agárdi Anita</oktato>
                
        <szak>Árnyékolás technikus</szak>
            
    </ora>
        
    <ora id="O5" tipus="elmelet">
                
        <targy>Mobilprogramozás alapjai (Mi)</targy>
                
        <idopont>
                        
            <nap>Hétfő</nap>
                        
            <tol>16:00</tol>
                        
            <ig>18:00</ig>
                    
        </idopont>
                
        <helyszin>Inf/101</helyszin>
                
        <oktato>Agárdi Anita</oktato>
                
        <szak>Árnyékolás technikus</szak>
            
    </ora>
        
    <ora id="O6" tipus="gyakorlat">
                
        <targy>Mobilprogramozás alapjai (Mi)</targy>
                
        <idopont>
                        
            <nap>Hétfő</nap>
                        
            <tol>18:00</tol>
                        
            <ig>20:00</ig>
                    
        </idopont>
                
        <helyszin>Inf/101</helyszin>
                
        <oktato>Agárdi Anita</oktato>
                
        <szak>Árnyékolás technikus</szak>
            
    </ora>
        
    <ora id="O7" tipus="elmelet">
                
        <targy>Windows rendszergazda (Wa)</targy>
                
        <idopont>
                        
            <nap>Kedd</nap>
                        
            <tol>8:00</tol>
                        
            <ig>10:00</ig>
                    
        </idopont>
                
        <helyszin>Inf/103</helyszin>
                
        <oktato>Wagner György</oktato>
                
        <szak>Árnyékolás technikus</szak>
            
    </ora>
        
    <ora id="O8" tipus="gyakorlat">
                
        <targy>Webes adatkezelő környezetek (Wk)</targy>
                
        <idopont>
                        
            <nap>Kedd</nap>
                        
            <tol>12:00</tol>
                        
            <ig>14:00</ig>
                    
        </idopont>
                
        <helyszin>Inf/101</helyszin>
                
        <oktato>Dr Bednarik László</oktato>
                
        <szak>Árnyékolás technikus</szak>
            
    </ora>
         
    <ora id="O9" tipus="gyakorlat">
                
        <targy>Elektrotechnika és elektronika (Ea)</targy>
                
        <idopont>
                        
            <nap>Szerda</nap>
                        
            <tol>8:00</tol>
                        
            <ig>10:00</ig>
                    
        </idopont>
                
        <helyszin>A1/310</helyszin>
                
        <oktato>Szabó Norbert</oktato>
                
        <szak>Árnyékolás technikus</szak>
            
    </ora>
        
    <ora id="O10" tipus="gyakorlat">
                
        <targy>Mesterséges intelinegcia (Ma)</targy>
                
        <idopont>
                        
            <nap>Szerda</nap>
                        
            <tol>10:00</tol>
                        
            <ig>12:00</ig>
                    
        </idopont>
                
        <helyszin>A1/218</helyszin>
                
        <oktato>Fazekas Levente</oktato>
                
        <szak>Árnyékolás technikus</szak>
            
    </ora>
        
    <ora id="O11" tipus="gyakorlat">
                
        <targy>Windows rendszergazda (Wa)</targy>
                
        <idopont>
                        
            <nap>Szerda</nap>
                        
            <tol>12:00</tol>
                        
            <ig>14:00</ig>
                    
        </idopont>
                
        <helyszin>Inf/101</helyszin>
                
        <oktato>Wagner György</oktato>
                
        <szak>Árnyékolás technikus</szak>
            
    </ora>
        
    <ora id="O12" tipus="elmelet">
                
        <targy>Webes adatkezelő környezetek (Wk)</targy>
                
        <idopont>
                        
            <nap>Szerda</nap>
                        
            <tol>14:00</tol>
                        
            <ig>16:00</ig>
                    
        </idopont>
                
        <helyszin>Inf/102</helyszin>
                
        <oktato>Dr Kovács László</oktato>
                
        <szak>Árnyékolás technikus</szak>
            
    </ora>
         
    <ora id="O13" tipus="elmelet">
                
        <targy>Mesterséges intelinegcia (Ma)</targy>
                
        <idopont>
                        
            <nap>Szerda</nap>
                        
            <tol>16:00</tol>
                        
            <ig>18:00</ig>
                    
        </idopont>
                
        <helyszin>A1/XXXII előadó</helyszin>
                
        <oktato>Kunné Dr. Tamás Judit</oktato>
                
        <szak>Árnyékolás technikus</szak>
            
    </ora>
    
</SZK_orarend>

=== szaloczy/Y4O4X0WebXML/Y4O4X0_1105/DomQueryY4O4X0/resources/Y4O4X0_orarend1.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><SZK_orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Y4O4X0_orarend1.xsd">

    <ora id="O0" tipus="elmelet">
        <targy>Elektrotechnika és elektronika</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>8:00</tol>
            <ig>10:00</ig>
        </idopont>
        <helyszin>A2/III. Előadó</helyszin>
        <oktato>Szabó Nórbert</oktato>
        <szak>Mérnökinformatika BSc</szak>
    </ora>
    <ora id="O1" tipus="elmelet">
        <targy>Webtechnológia I</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>A2/I. Előadó</helyszin>
        <oktato>Agárdi Anita</oktato>
        <szak>Mérnökinformatika BSc</szak>
    </ora>
    <ora id="O3" tipus="gyakorlat">
        <targy>Angol szaknyelv</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>A2/223</helyszin>
        <oktato>Dorkó Dóra</oktato>
        <szak>Mérnökinformatika BSc</szak>
    </ora>
    <ora id="O4" tipus="gyakorlat">
        <targy>Webtechnológia I</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>14:00</tol>
            <ig>16:00</ig>
        </idopont>
        <helyszin>Inf/101</helyszin>
        <oktato>Agárdi Anita</oktato>
        <szak>Mérnökinformatika BSc</szak>
    </ora>
    <ora id="O5" tipus="elmelet">
        <targy>Mobilprogramozás alapjai</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>16:00</tol>
            <ig>18:00</ig>
        </idopont>
        <helyszin>Inf/101</helyszin>
        <oktato>Agárdi Anita</oktato>
        <szak>Mérnökinformatika BSc</szak>
    </ora>
    <ora id="O6" tipus="gyakorlat">
        <targy>Mobilprogramozás alapjai</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>18:00</tol>
            <ig>20:00</ig>
        </idopont>
        <helyszin>Inf/101</helyszin>
        <oktato>Agárdi Anita</oktato>
        <szak>Mérnökinformatika BSc</szak>
    </ora>
    <ora id="O7" tipus="elmelet">
        <targy>Windows rendszergazda</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>8:00</tol>
            <ig>10:00</ig>
        </idopont>
        <helyszin>Inf/103</helyszin>
        <oktato>Wagner György</oktato>
        <szak>Mérnökinformatika BSc</szak>
    </ora>
    <ora id="O8" tipus="gyakorlat">
        <targy>Webes adatkezelő környezetek</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>Inf/101</helyszin>
        <oktato>Dr Bednarik László</oktato>
        <szak>Mérnökinformatika BSc</szak>
    </ora>
     <ora id="O9" tipus="gyakorlat">
        <targy>Elektrotechnika és elektronika</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>8:00</tol>
            <ig>10:00</ig>
        </idopont>
        <helyszin>A1/310</helyszin>
        <oktato>Szabó Norbert</oktato>
        <szak>Mérnökinformatika BSc</szak>
    </ora>
    <ora id="O10" tipus="gyakorlat">
        <targy>Mesterséges intelinegcia</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>A1/218</helyszin>
        <oktato>Fazekas Levente</oktato>
        <szak>Mérnökinformatika BSc</szak>
    </ora>
    <ora id="O11" tipus="gyakorlat">
        <targy>Windows rendszergazda</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>Inf/101</helyszin>
        <oktato>Wagner György</oktato>
        <szak>Mérnökinformatika BSc</szak>
    </ora>
    <ora id="O12" tipus="elmelet">
        <targy>Webes adatkezelő környezetek</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>14:00</tol>
            <ig>16:00</ig>
        </idopont>
        <helyszin>Inf/102</helyszin>
        <oktato>Dr Kovács László</oktato>
        <szak>Mérnökinformatika BSc</szak>
    </ora>
     <ora id="O13" tipus="elmelet">
        <targy>Mesterséges intelinegcia</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>16:00</tol>
            <ig>18:00</ig>
        </idopont>
        <helyszin>A1/XXXII előadó</helyszin>
        <oktato>Kunné Dr. Tamás Judit</oktato>
        <szak>Mérnökinformatika BSc</szak>
    </ora>
</SZK_orarend>
