=== szaloczy/Y4O4X0WebXML/Y4O4X0_1126/xPathY4O4X0/target/classes/resources/studentY4O4X0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="korTipus">
        <xs:restriction base="xs:int">
            <xs:minExclusive value="18"></xs:minExclusive>
            <xs:maxExclusive value="100"></xs:maxExclusive>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="studentTipus">
        <xs:sequence>
            <xs:element name="keresztnev" type="xs:string"></xs:element>
            <xs:element name="vezeteknev" type="xs:string"></xs:element>
            <xs:element name="becenev" type="xs:string"></xs:element>
            <xs:element name="kor" type="korTipus"></xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:element name="class">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" type="studentTipus" minOccurs="3" maxOccurs="100"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== szaloczy/Y4O4X0WebXML/Y4O4X0_1126/xPathY4O4X0/src/resources/studentY4O4X0.xml
<?xml version="1.0" encoding="UTF-8"?>
<class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="studentY4O4X0.xsd">
    <student id="s1">
        <keresztnev>P치l</keresztnev>
        <vezeteknev>Kiss</vezeteknev>
        <becenev>Palika</becenev>
        <kor>23</kor>
    </student>
    <student id="s2">
        <keresztnev>J칩zsef</keresztnev>
        <vezeteknev>Nagy</vezeteknev>
        <becenev>J칩zsi</becenev>
        <kor>20</kor>
    </student>
    <student id="s3">
        <keresztnev>Benedek</keresztnev>
        <vezeteknev>Szab칩</vezeteknev>
        <becenev>Beni</becenev>
        <kor>21</kor>
    </student>
</class>
