=== szaloczy/Y4O4X0WebXML/XMLTaskY4O4X0/XMLSchemaY4O4X0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

        <!--Email tipus létrehozása, korlátozása reguláris kifejezéssel-->
        <xs:simpleType name="emailTipus">
            <xs:restriction base="xs:string">
                <!--regex az adószámra: 
                [0-9]{8}: Pontosan 8 számjegy.
                -: Egy kötőjel.
                [0-9]{1}: Pontosan 1 számjegy.
                -: Egy kötőjel.
                [0-9]{2}: Pontosan 2 számjegy.-->
                <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>

        <!--Adoszam tipus létrehozása, korlátozása reguláris kifejezéssel-->
        <xs:simpleType name="adoszamTipus">
            <xs:restriction base="xs:string">
                <!--regex az adószámra: 
                [0-9]{8}: Pontosan 8 számjegy.
                -: Egy kötőjel.
                [0-9]{1}: Pontosan 1 számjegy.
                -: Egy kötőjel.
                [0-9]{2}: Pontosan 2 számjegy.-->
                <xs:pattern value="[0-9]{8}-[0-9]{1}-[0-9]{2}"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>

        <!--Pozício tipus létrehozása, korlátozása adott értékekre-->
        <xs:simpleType name="pozicioTipus">
            <xs:restriction base="xs:string">
                <xs:enumeration value="Szoftverfejlesztő"></xs:enumeration>
                <xs:enumeration value="Projekt menedzser"></xs:enumeration>
                <xs:enumeration value="Mérnök"></xs:enumeration>
                <xs:enumeration value="Aszisztens"></xs:enumeration>
                <xs:enumeration value="Tesztelő"></xs:enumeration>
            </xs:restriction>
        </xs:simpleType>

        <!--Előrehaladás tipus létrehozása, korlátozása adott intervallumra-->
        <xs:simpleType name="elorehaladasTipus">
                <xs:restriction base="xs:int">
                    <xs:minExclusive value="0"></xs:minExclusive>
                    <xs:maxExclusive value="100"></xs:maxExclusive>
                </xs:restriction>
        </xs:simpleType>

        <!--Emelet tipus létrehozása, korlátozása adott értékekre-->
        <xs:simpleType name="emeletTipus">
            <xs:restriction base="xs:int">
                <xs:minExclusive value="1"></xs:minExclusive>
                <xs:maxExclusive value="6"></xs:maxExclusive>
            </xs:restriction>
        </xs:simpleType>

        <!--Cím tipus létrehozása, gyerekelemek definilása-->
        <xs:complexType name="cimTipus">
            <xs:sequence>
                <xs:element name="varos" type="xs:string"></xs:element>
                <xs:element name="utca" type="xs:string"></xs:element>
                <xs:element name="hazszam" type="xs:int"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <!--Ügyfél tipus létrehozása, gyerekelemek definilása-->
        <xs:complexType name="ugyfelTipus">
            <xs:sequence>
                <xs:element name="nev" type="xs:string"></xs:element>
                <xs:element name="adoszam" type="adoszamTipus"></xs:element>
                <xs:element name="cim" type="cimTipus"></xs:element>
                <xs:element name="email" type="emailTipus"></xs:element>
            </xs:sequence>
            <xs:attribute name="ukod" type="xs:string" use="required"></xs:attribute>
            <xs:attribute name="pkod" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>

        <!--Munkaidő tipus létrehozása, gyerekelemek definilása-->
        <xs:complexType name="munkaidoTipus">
            <xs:sequence>
                <xs:element name="tol" type="xs:time"></xs:element>
                <xs:element name="ig" type="xs:time"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <!--Projekt tipus létrehozása, gyerekelemek  és attribútumai definilása-->
        <xs:complexType name="projektTipus" mixed="true">
            <xs:sequence>
                <xs:element name="nev" type="xs:string"></xs:element>
                <xs:element name="felelos" type="xs:string"></xs:element>
                <xs:element name="hatarido" type="xs:date"></xs:element>
            </xs:sequence>
            <xs:attribute name="pkod" type="xs:string" use="required"></xs:attribute>
            <xs:attribute name="rkod" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>

        <!--Beosztás tipus létrehozása, gyerekelemek  és attribútumai definilása-->
        <xs:complexType name="beosztasTipus">
            <xs:sequence>
                <xs:element name="munkaido" type="munkaidoTipus"></xs:element>
                <xs:element name="pozicio" type="pozicioTipus"></xs:element>
            </xs:sequence>
            <xs:attribute name="bkod" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>

        <!--Dolgozo tipus létrehozása, gyerekelemek  és attribútumai definilása-->
        <xs:complexType name="dolgozoTipus" mixed="true">
            <xs:sequence>
                <xs:element name="fizetes" type="xs:int"></xs:element>
                <xs:element name="vegzettseg" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="belepesiDatum" type="xs:date"></xs:element>
                <xs:element name="beosztas" type="beosztasTipus"></xs:element>
                <xs:element name="nev" type="xs:string"></xs:element>
            </xs:sequence>
            <xs:attribute name="dkod" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    
        <!--Csapat tipus létrehozása, gyerekelemek  és attribútumai definilása-->
        <xs:complexType name="csapatTipus" mixed="true">
            <xs:sequence>
                <xs:element name="vezeto" type="xs:string"></xs:element>
                <xs:element name="letszam" type="xs:int"></xs:element>
                <xs:element name="elorehaladas" type="elorehaladasTipus"></xs:element>
                <xs:element name="dolgozo" type="dolgozoTipus" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute name="cskod" type="xs:string" use="required"></xs:attribute>
            <xs:attribute name="rkod" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
 
        <!--Részleg egyed létrehozása, gyerekelemek és attribútumai definilása-->
    <xs:element name="reszleg">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="nev" type="xs:string"></xs:element>
                <xs:element name="emelet" type="emeletTipus"></xs:element>
                <xs:element name="letszam" type="xs:int"></xs:element>
                <xs:element name="csapat" type="csapatTipus" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="projekt" type="projektTipus" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element name="ugyfel" type="ugyfelTipus" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute name="rkod" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>

        <!--Vállalat gyökérelem létrehozása (globális), gyerekelemek definiálása-->
    <xs:element name="vallalat">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="reszleg" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <!--Elsődleges kulcsok-->
        <xs:key name="reszleg_kulcs">
            <xs:selector xpath="reszleg"></xs:selector>
            <xs:field xpath="@rkod"></xs:field>
        </xs:key>
        <xs:key name="csapat_kulcs">
            <xs:selector xpath="csapat"></xs:selector>
            <xs:field xpath="@cskod"></xs:field>
        </xs:key>
        <xs:key name="projekt_kulcs">
            <xs:selector xpath="projekt"></xs:selector>
            <xs:field xpath="@pkod"></xs:field>
        </xs:key>
        <xs:key name="ugyfel_kulcs">
            <xs:selector xpath="ugyfel"></xs:selector>
            <xs:field xpath="@ukod"></xs:field>
        </xs:key>
        <xs:key name="dolgozo_kulcs">
            <xs:selector xpath="dolgozo"></xs:selector>
            <xs:field xpath="@dkod"></xs:field>
        </xs:key>

        <!--Idegen kulcsok-->
        <xs:keyref name="csapat_tartozik_reszleg_kulcs" refer="reszleg_kulcs">
            <xs:selector xpath="csapat"></xs:selector>
            <xs:field xpath="@rkod"></xs:field>
        </xs:keyref>
        <xs:keyref name="projekt_tartozik_reszleg_kulcs" refer="reszleg_kulcs">
            <xs:selector xpath="projekt"></xs:selector>
            <xs:field xpath="@rkod"></xs:field>
        </xs:keyref>
        <xs:keyref name="ugyfel_rendel_projekt_kulcs" refer="projekt_kulcs">
            <xs:selector xpath="ugyfel"></xs:selector>
            <xs:field xpath="@pkod"></xs:field>
        </xs:keyref>
        <xs:keyref name="dolgozo_tartozik_csapat_kulcs" refer="csapat_kulcs">
            <xs:selector xpath="csapat/dolgozo"></xs:selector>
            <xs:field xpath="@cskod"></xs:field>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== szaloczy/Y4O4X0WebXML/XMLTaskY4O4X0/XMLY4O4X0.xml
<?xml version="1.0" encoding="UTF-8" ?>
<vallalat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="XMLSchemaY4O4X0.xsd">
 <!--Részlegek-->
 <reszleg rkod="r1">
    <nev>Elektronika</nev>
    <emelet>2</emelet>
    <letszam>12</letszam>
    <!--Csapatok-->
    <csapat cskod="cs1">
        <vezeto>Szabó Ernő</vezeto>
        <letszam>8</letszam>
        <elorehaladas>30</elorehaladas>
        <!--Dolgozok-->
        <dolgozo dkod="d1">
            <fizetes>3000000</fizetes>
            <vegzettseg>Bsc diploma</vegzettseg>
            <belepesiDatum>2006-02-02</belepesiDatum>
            <beosztas bkod="b1">
                <munkaido>
                    <tol>10:00:00</tol>
                    <ig>18:00:00</ig>
                </munkaido>
                <pozicio>Szoftverfejlesztő</pozicio>
            </beosztas>
        </dolgozo>
        <dolgozo dkod="d2">
            <fizetes>2000</fizetes>
            <vegzettseg>Középfokú végzettség</vegzettseg>
            <belepesiDatum>2010-01-21</belepesiDatum>
            <beosztas bkod="bkod2">
                <munkaido>
                    <tol>10:00:00</tol>
                    <ig>18:00:00</ig>
                </munkaido>
                <pozicio>Tesztelő</pozicio>
            </beosztas>
        </dolgozo>
        <dolgozo dkod="d3">
            <fizetes>300000</fizetes>
            <vegzettseg>Bsc diploma</vegzettseg>
            <belepesiDatum>2000-03-03</belepesiDatum>
            <beosztas bkod="bkod3">
                <munkaido>
                    <tol>10:00:00</tol>
                    <ig>18:00:00</ig>
                </munkaido>
                <pozicio>Tesztelő</pozicio>
            </beosztas>
        </dolgozo>
    </csapat>
    <csapat cskod="cs2">
        <vezeto>Nagy István</vezeto>
        <letszam>43</letszam>
        <elorehaladas>75</elorehaladas>
        <dolgozo dkod="d4">
            <fizetes>242000</fizetes>
            <vegzettseg>Bsc diploma</vegzettseg>
            <belepesiDatum>2017-03-08</belepesiDatum>
            <beosztas bkod="cs1">
                <munkaido>
                    <tol>10:00:00</tol>
                    <ig>18:00:00</ig>
                </munkaido>
                <pozicio>Projekt menedzser</pozicio>
            </beosztas>
        </dolgozo>
    </csapat>
    <csapat cskod="cs3">
        <vezeto>Kovács András</vezeto>
        <letszam>15</letszam>
        <elorehaladas>45</elorehaladas>
        <dolgozo dkod="d5">
            <fizetes>3000000</fizetes>
            <vegzettseg>Bsc diploma</vegzettseg>
            <belepesiDatum>2011-11-10</belepesiDatum>
            <beosztas bkod="cs1">
                <munkaido>
                    <tol>10:00:00</tol>
                    <ig>18:00:00</ig>
                </munkaido>
                <pozicio>Szoftverfejlesztő</pozicio>
            </beosztas>
        </dolgozo>
    </csapat>
    <!--Projektek-->
    <projekt pkod="p1">
        <nev>Fejlesztési projekt</nev>
        <felelos>Szabó Ernő</felelos>
        <hatarido>2024-02-02</hatarido>
    </projekt>
    <projekt pkod="p7">
        <nev>Karbantartási projekt</nev>
        <felelos>Kovács András</felelos>
        <hatarido>2024-05-15</hatarido>
    </projekt>
    <projekt pkod="p4">
        <nev>Tesztelési projekt</nev>
        <felelos>Nagy István</felelos>
        <hatarido>2024-03-30</hatarido>
    </projekt>
    <!--Ügyfelek-->
    <ugyfel ukod="u1">
        <nev>János és Társai Kft.</nev>
        <adoszam>12345678-1-12</adoszam>
        <cim>
            <varos>Miskolc</varos>
            <utca>Petőfi út</utca>
            <hazszam>22</hazszam>
        </cim>
        <email>janostarsai@gmail.com</email>
    </ugyfel>
</reszleg>
<!--Részleg-->
<reszleg rkod="r2">
    <nev>Marketing</nev>
    <emelet>3</emelet>
    <letszam>10</letszam>
    <csapat cskod="cs1">
        <vezeto>Kiss Anna</vezeto>
        <letszam>5</letszam>
        <elorehaladas>60</elorehaladas>
        <dolgozo dkod="d1">
            <fizetes>4000000</fizetes>
            <vegzettseg>Msc diploma</vegzettseg>
            <belepesiDatum>2015-05-12</belepesiDatum>
            <beosztas bkod="b1">
                <munkaido>
                    <tol>09:00:00</tol>
                    <ig>17:00:00</ig>
                </munkaido>
                <pozicio>Tesztelő</pozicio>
            </beosztas>
        </dolgozo>
        <dolgozo dkod="d2">
            <fizetes>3500000</fizetes>
            <vegzettseg>Bsc diploma</vegzettseg>
            <belepesiDatum>2018-03-04</belepesiDatum>
            <beosztas bkod="bkod2">
                <munkaido>
                    <tol>09:00:00</tol>
                    <ig>17:00:00</ig>
                </munkaido>
                <pozicio>Szoftverfejlesztő</pozicio>
            </beosztas>
        </dolgozo>
        <dolgozo dkod="d3">
            <fizetes>2500000</fizetes>
            <vegzettseg>Bsc diploma</vegzettseg>
            <belepesiDatum>2017-08-19</belepesiDatum>
            <beosztas bkod="bkod3">
                <munkaido>
                    <tol>09:00:00</tol>
                    <ig>17:00:00</ig>
                </munkaido>
                <pozicio>Mérnök</pozicio>
            </beosztas>
        </dolgozo>
    </csapat>
    <csapat cskod="cs2">
        <vezeto>Nagy Zoltán</vezeto>
        <letszam>5</letszam>
        <elorehaladas>45</elorehaladas>
        <dolgozo dkod="d4">
            <fizetes>3000000</fizetes>
            <vegzettseg>Bsc diploma</vegzettseg>
            <belepesiDatum>2020-09-11</belepesiDatum>
            <beosztas bkod="cs1">
                <munkaido>
                    <tol>09:00:00</tol>
                    <ig>17:00:00</ig>
                </munkaido>
                <pozicio>Projekt menedzser</pozicio>
            </beosztas>
        </dolgozo>
    </csapat>
    <projekt pkod="p2">
        <nev>Brand Építés</nev>
        <felelos>Kiss Anna</felelos>
        <hatarido>2024-03-15</hatarido>
    </projekt>
    <projekt pkod="p8">
        <nev>SEO Optimalizálás</nev>
        <felelos>Nagy Zoltán</felelos>
        <hatarido>2024-04-20</hatarido>
    </projekt>
    <ugyfel ukod="u2">
        <nev>XY Kft.</nev>
        <adoszam>87654321-1-12</adoszam>
        <cim>
            <varos>Debrecen</varos>
            <utca>Fő utca</utca>
            <hazszam>10</hazszam>
        </cim>
        <email>xykft@domain.com</email>
    </ugyfel>
</reszleg>
<reszleg rkod="r3">
    <nev>HR</nev>
    <emelet>2</emelet>
    <letszam>6</letszam>
    <csapat cskod="cs1">
        <vezeto>Tóth Péter</vezeto>
        <letszam>3</letszam>
        <elorehaladas>80</elorehaladas>
        <dolgozo dkod="d1">
            <fizetes>5000000</fizetes>
            <vegzettseg>Msc diploma</vegzettseg>
            <belepesiDatum>2012-10-10</belepesiDatum>
            <beosztas bkod="b1">
                <munkaido>
                    <tol>09:00:00</tol>
                    <ig>17:00:00</ig>
                </munkaido>
                <pozicio>Projekt menedzser</pozicio>
            </beosztas>
        </dolgozo>
        <dolgozo dkod="d2">
            <fizetes>3500000</fizetes>
            <vegzettseg>Bsc diploma</vegzettseg>
            <belepesiDatum>2015-05-22</belepesiDatum>
            <beosztas bkod="bkod2">
                <munkaido>
                    <tol>09:00:00</tol>
                    <ig>17:00:00</ig>
                </munkaido>
                <pozicio>Mérnök</pozicio>
            </beosztas>
        </dolgozo>
        <dolgozo dkod="d3">
            <fizetes>3000000</fizetes>
            <vegzettseg>Bsc diploma</vegzettseg>
            <belepesiDatum>2018-07-05</belepesiDatum>
            <beosztas bkod="bkod3">
                <munkaido>
                    <tol>09:00:00</tol>
                    <ig>17:00:00</ig>
                </munkaido>
                <pozicio>Mérnök</pozicio>
            </beosztas>
        </dolgozo>
    </csapat>
    <csapat cskod="cs2">
        <vezeto>Varga Eszter</vezeto>
        <letszam>3</letszam>
        <elorehaladas>70</elorehaladas>
        <dolgozo dkod="d4">
            <fizetes>2500000</fizetes>
            <vegzettseg>Bsc diploma</vegzettseg>
            <belepesiDatum>2019-11-14</belepesiDatum>
            <beosztas bkod="cs1">
                <munkaido>
                    <tol>09:00:00</tol>
                    <ig>17:00:00</ig>
                </munkaido>
                <pozicio>Aszisztens</pozicio>
            </beosztas>
        </dolgozo>
    </csapat>
    <projekt pkod="p3">
        <nev>Alkalmazotti elégedettség felmérés</nev>
        <felelos>Tóth Péter</felelos>
        <hatarido>2024-06-30</hatarido>
    </projekt>
    <projekt pkod="p9">
        <nev>Jutalom és elismerés program</nev>
        <felelos>Varga Eszter</felelos>
        <hatarido>2024-08-15</hatarido>
    </projekt>
    <ugyfel ukod="u3">
        <nev>ABC Tanácsadó Kft.</nev>
        <adoszam>11223344-1-12</adoszam>
        <cim>
            <varos>Szeged</varos>
            <utca>Kossuth Lajos utca</utca>
            <hazszam>15</hazszam>
        </cim>
        <email>abctanacsado@gmail.com</email>
    </ugyfel>
</reszleg>
</vallalat>
